# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\CSTI-ModEditor\NewItem.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewItem(object):
    def setupUi(self, NewItem):
        NewItem.setObjectName("NewItem")
        NewItem.resize(539, 93)
        self.gridLayout = QtWidgets.QGridLayout(NewItem)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(NewItem)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(NewItem)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.buttonBox = QtWidgets.QDialogButtonBox(NewItem)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(NewItem)
        self.buttonBox.accepted.connect(NewItem.accept) # type: ignore
        self.buttonBox.rejected.connect(NewItem.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(NewItem)

    def retranslateUi(self, NewItem):
        _translate = QtCore.QCoreApplication.translate
        NewItem.setWindowTitle(_translate("NewItem", "New Mod"))
        self.label.setText(_translate("NewItem", "Enter the name"))
