# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\CSTI-ModEditor\NewMod.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewMod(object):
    def setupUi(self, NewMod):
        NewMod.setObjectName("NewMod")
        NewMod.resize(266, 87)
        self.gridLayout = QtWidgets.QGridLayout(NewMod)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(NewMod)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(NewMod)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.buttonBox = QtWidgets.QDialogButtonBox(NewMod)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(NewMod)
        self.buttonBox.accepted.connect(NewMod.accept) # type: ignore
        self.buttonBox.rejected.connect(NewMod.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(NewMod)

    def retranslateUi(self, NewMod):
        _translate = QtCore.QCoreApplication.translate
        NewMod.setWindowTitle(_translate("NewMod", "Dialog"))
        self.label.setText(_translate("NewMod", "输入Mod名字"))
