# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\CSTI-ModEditor\Select.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Select(object):
    def setupUi(self, Select):
        Select.setObjectName("Select")
        Select.resize(458, 127)
        self.gridLayout = QtWidgets.QGridLayout(Select)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(Select)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(Select)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.comboBox = QtWidgets.QComboBox(Select)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout.addWidget(self.comboBox)
        self.horizontalLayout_CheckBox = QtWidgets.QHBoxLayout()
        self.horizontalLayout_CheckBox.setObjectName("horizontalLayout_CheckBox")
        self.verticalLayout.addLayout(self.horizontalLayout_CheckBox)
        self.horizontalLayout_CheckBox2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_CheckBox2.setObjectName("horizontalLayout_CheckBox2")
        self.verticalLayout.addLayout(self.horizontalLayout_CheckBox2)
        self.buttonBox = QtWidgets.QDialogButtonBox(Select)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Select)
        self.buttonBox.accepted.connect(Select.accept) # type: ignore
        self.buttonBox.rejected.connect(Select.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Select)

    def retranslateUi(self, Select):
        _translate = QtCore.QCoreApplication.translate
        Select.setWindowTitle(_translate("Select", "选择"))
        self.label.setText(_translate("Select", "搜索框"))
